version: '3'
services:
  influxdb:
    image: influxdb
    container_name: octo-influxdb
    environment:
      - INFLUXDB_DB=energy
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
